#!/usr/bin/env python
# coding: utf-8

import os, sys

comandos = sys.argv
comando = comandos.pop()

    
if comando=="-all" : 
    os.system("sudo apt-get update")
    print "Repositórios atualizados"
    os.system("sudo apt-get upgrade -y")
    print("Pacotes atualizados")
    os.system("sudo apt-get dist-upgrade -y")
    print("Distribuição atualizada")

else:
    os.system("sudo apt-get update")
    print "Os repositórios foram atualizados"

os.system("sudo apt-get autoremove -y")
print("Sistema atualizado, e limpo")
    


